### ISSUE TITLE
App works great, but nothing plays

### ISSUE THREAD

**Issue by plastikhub** [AnanthVivekanand/spotify-adblock#14]
Went through all instructions, everything seems to be working ok, except no song will play. Is this something to do with the login5.spotify.com being blocked?

**Comment by AnanthVivekanand** [comment]
I think it is indeed related to that. This is essentially the same as issue #3, we tried to unblock login5.spotify.com and found that ads come through.

You can try and add `login5.spotify.com` to `whitelist.js` (more details in #3) but as I explain, I can't whitelist without breaking functionality for other users.

**Comment by henryli17** [comment]
Seems like downgrading Spotify to version 1.0.80 or lower solves this problem. Once the older version of Spotify is installed, open up Spotify and then run [this shell script](https://github.com/julionc/dotfiles/blob/9990859cf4de0536d0d2b4351c3f19dec9fdfd48/osx/doNotUpdateSpotify.sh) to block updates.

**Comment by pseudobacon** [comment]
Confirmed working after downgrading to 1.0.87.491

**Comment by pseudobacon** [comment]
The lower version works as in music plays, but ads creep in unfortunately

**Comment by henryli17** [comment]
Have a look at the workaround I made, been using it for a few months with no problems.

https://github.com/henryli17/macOsSpotifyAdblocker

**Comment by AnanthVivekanand** [comment]
Alright, so this is a confirmed bug. Another workaround in addition to @henryli17's project is to use the builtin man-in-the-middle filtering, the instructions for that are at the bottom of the README. I've been using the mitm-proxy branch for several months and its been working with no flaws, so I decided to go ahead and merge it into master.

**Comment by AnanthVivekanand** [comment]
From now on, using mitm.js is the recommended approach, so this issue is resolved.
