### ISSUE TITLE
Update Node.JS

### ISSUE THREAD

**Issue by coleslamfreckle3** [AnanthVivekanand/spotify-adblock#17]
How would I update Node.js? My error is npm ERR! Darwin 19.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! spotify-adblock-macos@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spotify-adblock-macos@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spotify-adblock-macos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spotify-adblock-macos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spotify-adblock-macos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ashwins.kumar/spotify-adblock-macos/npm-debug.log
(base) ashwins.kumar@Ashwins-iMac spotify-adblock-macos % nvm install node --rei

**Comment by AnanthVivekanand** [comment]
As the error suggests, update nodejs. Version 6.11 is pretty old, personally I use 11.15. Please reopen if the error persists after updating.

**Comment by coleslamfreckle3** [comment]
Okay
