### ISSUE TITLE
[Question] Why do you call it macos, it should work on all OS's since they all share the same eletron app

### ISSUE THREAD

**Issue by filipef101** [AnanthVivekanand/spotify-adblock#20]
title

**Comment by AnanthVivekanand** [comment]
Indeed, this should work on all OS's. Also, this isn't an electron app, this is raw Nodejs app and doesn't ship with any rendering/GUI. I'll consider changing the name to maybe just `spotify-adblock`.

**Comment by filipef101** [comment]
I mean, the spotify app is eletron. Yeah, it could get more popular that way

**Comment by srihari10826** [comment]
does this work on Linux..by Srihari Embar

**Comment by AnanthVivekanand** [comment]
Hey Srihari! Yes, this would work on Linux but I would recommend that you use [this](https://github.com/abba23/spotify-adblock-linux) instead of my project.

**Comment by srihari10826** [comment]
how about on windows 10, I have few more question,s..what is your #, your friend from Rice middle school

**Comment by AnanthVivekanand** [comment]
Renamed to "spotify-adblock" @filipef101.
