### ISSUE TITLE
Only music which i already have added to playlists and which i have liked work.Home,search friends do not work

### ISSUE THREAD

**Issue by rickyrorton** [AnanthVivekanand/spotify-adblock#24]
![image](https://user-images.githubusercontent.com/74890659/113602573-d3839500-9653-11eb-9d1f-cbe033f52cc8.png)

**Comment by AnanthVivekanand** [comment]
This seems similar to #29. Could you try the latest version and see whether the issue still occurs?

**Comment by rickyrorton** [comment]
Thank you ananth will try the latest version and check if the issue still persist

Good job on the adblocker btw

**Comment by rickyrorton** [comment]
![image](https://user-images.githubusercontent.com/74890659/117536244-0500cf00-b00b-11eb-86e9-b4ae223160aa.png)
Works perfectly thank you Ananth for updating the files 
Regards
Rickyrorton
