### ISSUE TITLE
Search and startpage and friends sidebar not working with new version "1.1.56.595.g2d2da0de-a"

### ISSUE THREAD

**Issue by AutMai** [AnanthVivekanand/spotify-adblock#26]
startpage not loading
and search results not loading
friends sidebar not showing

**Comment by pickaxe828** [comment]
Different platforms have different solutions to install the cert stuff. You
can go to google and search for how (like “how to install certificate
windows”)

**Comment by AutMai** [comment]
Does not work

**Comment by AnanthVivekanand** [comment]
Cannot reproduce and issues seems to have lost activity. Am on 1.1.58.820 and everything works perfectly for me. Please reopen with a log and steps to reproduce.
