### ISSUE TITLE
Run without the cmd window keeps open (On Windows)

### ISSUE THREAD

**Issue by pickaxe828** [AnanthVivekanand/spotify-adblock#28]
It would love to see if there is a way to run this without require the cmd keeps opening because that is kinda annoying. (MITM mode)

**Comment by AngryKiller** [comment]
You can use a tool such as PM2 to run it as a daemon and other things, such as running it at boot, etc

**Comment by pickaxe828** [comment]
> You can use a tool such as PM2 to run it as a daemon and other things, such as running it at boot, etc

How about on Windows?

**Comment by AngryKiller** [comment]
I'm pretty sure PM2 also works on Windows

**Comment by AnanthVivekanand** [comment]
Hm, I've been thinking about compiling binary versions of the proxy. This would essentially wrap the node.js script with a node.js binary depending on the OS into a single binary (exe on Windows), which would make it easier to start since it wouldn't be necessary to use command line. Command line would still be needed to trust the root certification, however. 

Would compiling to an exe make it easier to have it start on login? I haven't used Windows in quite a while, but I think the process is something like making a shortcut to an exe in a certain folder.

**Comment by pickaxe828** [comment]
> Hm, I've been thinking about compiling binary versions of the proxy. This would essentially wrap the node.js script with a node.js binary depending on the OS into a single binary (exe on Windows), which would make it easier to start since it wouldn't be necessary to use command line. Command line would still be needed to trust the root certification, however.
> 
> Would compiling to an exe make it easier to have it start on login? I haven't used Windows in quite a while, but I think the process is something like making a shortcut to an exe in a certain folder.

Exactly. I added a VB script in the folder that starts the `node mitm.js` without opening a cmd window
And I also created a shortcut to the VB script in the `shell:startup` folder to make sure the proxy starts every time when I turn on my computer.

**Comment by jckefan** [comment]
> > Hm, I've been thinking about compiling binary versions of the proxy. This would essentially wrap the node.js script with a node.js binary depending on the OS into a single binary (exe on Windows), which would make it easier to start since it wouldn't be necessary to use command line. Command line would still be needed to trust the root certification, however.
> > Would compiling to an exe make it easier to have it start on login? I haven't used Windows in quite a while, but I think the process is something like making a shortcut to an exe in a certain folder.
> 
> I added a VB script in the folder that starts the `node mitm.js` without opening a cmd window
> And I also created a shortcut to the VB script in the `shell:startup` folder to make sure the proxy starts every time when I turn on my computer.

Mind sharing the script? Thanks

**Comment by pickaxe828** [comment]
> > > Hm, I've been thinking about compiling binary versions of the proxy. This would essentially wrap the node.js script with a node.js binary depending on the OS into a single binary (exe on Windows), which would make it easier to start since it wouldn't be necessary to use command line. Command line would still be needed to trust the root certification, however.
> > > Would compiling to an exe make it easier to have it start on login? I haven't used Windows in quite a while, but I think the process is something like making a shortcut to an exe in a certain folder.
> > 
> > 
> > I added a VB script in the folder that starts the `node mitm.js` without opening a cmd window
> > And I also created a shortcut to the VB script in the `shell:startup` folder to make sure the proxy starts every time when I turn on my computer.
> 
> Mind sharing the script? Thanks

@jckefan 
```vbs
Set oShell = CreateObject ("Wscript.Shell")
Dim strArgs
StrArgs = "node ""D:\APP\Spotify Ad Block\spotify-adblock-macos\mitm.js"" "
oShell.Run strArgs, 0, false
```
Put this code in a `.vbs` file in the `./spotify-adblock-macos` so you don't need to certify the certificates everywhere
Then make a shortcut to this file in `shell:startup` folder
So this will ad block start every time the computer starts

**Comment by jckefan** [comment]
> > > > Hm, I've been thinking about compiling binary versions of the proxy. This would essentially wrap the node.js script with a node.js binary depending on the OS into a single binary (exe on Windows), which would make it easier to start since it wouldn't be necessary to use command line. Command line would still be needed to trust the root certification, however.
> > > > Would compiling to an exe make it easier to have it start on login? I haven't used Windows in quite a while, but I think the process is something like making a shortcut to an exe in a certain folder.
> > > 
> > > 
> > > I added a VB script in the folder that starts the `node mitm.js` without opening a cmd window
> > > And I also created a shortcut to the VB script in the `shell:startup` folder to make sure the proxy starts every time when I turn on my computer.
> > 
> > 
> > Mind sharing the script? Thanks
> 
> @jckefan
> 
> ```vbnet
> Set oShell = CreateObject ("Wscript.Shell")
> Dim strArgs
> StrArgs = "node ""D:\APP\Spotify Ad Block\spotify-adblock-macos\mitm.js"" "
> oShell.Run strArgs, 0, false
> ```
> 
> Put this code in a `.vbs` file in the `./spotify-adblock-macos` so you don't need to certify the certificates everywhere
> Then make a shortcut to this file in `shell:startup` folder
> So this will ad block start every time the computer starts

It worked thank you so much for the script.🥰
