### ISSUE TITLE
Home page not loading on latest spotify. (mitm.js)

### ISSUE THREAD

**Issue by pickaxe828** [AnanthVivekanand/spotify-adblock#29]
After updating my spotify, this ad-block is kinda broken.

![image](https://user-images.githubusercontent.com/41852594/117310507-ec32d500-aeb5-11eb-809e-1697964c8fab.png)

**Comment by AnanthVivekanand** [comment]
Latest commit should fix this. For reference, the MITM whitelist is mostly taken from the [spotify-adblock-linux project](https://github.com/abba23/spotify-adblock-linux/blob/master/whitelist.h). If something like this happens in the future, feel free to update mitm-utils/whitelist-mitm.js and send a pull request.
