### ISSUE TITLE
Violating Spotify TOS is it something we should care about?

### ISSUE THREAD

**Issue by rickyrorton** [AnanthVivekanand/spotify-adblock#31]
![image](https://user-images.githubusercontent.com/74890659/120974834-a487bd80-c781-11eb-9965-001c9c728f18.png)
So apparently the TOS states that "circumventing or blocking advertisements in the Spotify Service, or creating or distributing tools designed to block advertisements in the Spotify Service" is breaking TOS just thought i wanted to bring this to your attention

**Comment by rickyrorton** [comment]
Is it something we will get banned for ? By using the proxy and blocking ads?

**Comment by CharlieS1103** [comment]
Shhhhhhhhh.

**Comment by Green-Thanos** [comment]
shhh you dont see anything

**Comment by pickaxe828** [comment]
> Is it something we will get banned for ? By using the proxy and blocking ads?

If you think you will get banned for using this, then just don't use it 🤣

**Comment by akash-258** [comment]
I have been blocking ads since 4 years, nothing happened.

**Comment by rickyrorton** [comment]
> y'all keep your fucking nugget month shut! Nobody is forcing you to use it, if you fear, then this isn't for you! Stop using it then. What you are bitch'in about? Ugh?

Ayo why you gotta be rude about it smh calm yo fucking ass down
