### ISSUE TITLE
Logout, Friends list, among others not working.

### ISSUE THREAD

**Issue by CharlieS1103** [AnanthVivekanand/spotify-adblock#33]
On logout you recieve : 
`Uncaught (in promise) Error: POST request to sp://desktop/v1/logout failed with status code 404
    at c.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)`

UpgradeStatus for friends list: 
`xpui.js:1 Error: SUB request to sp://desktop/v1/upgrade/status failed with status code 404
    at c.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
n @ xpui.js:1
onSuccess @ xpui.js:1
onSuccess @ xpui.js:1
xpui.js:1 Uncaught (in promise) Error: P`

**Comment by AnanthVivekanand** [comment]
Where are these errors occurring? Are these in the Spotify log or mitm.js log?

**Comment by CharlieS1103** [comment]
@AnanthVivekanand These errors are in the spotify console, would you like me to send mitm.js log as well?

**Comment by CharlieS1103** [comment]
<img width="730" alt="Screen Shot 2021-06-23 at 6 44 40 PM" src="https://user-images.githubusercontent.com/60494758/123177330-12ef9f80-d453-11eb-9339-69a533bf0f88.png">

**Comment by CharlieS1103** [comment]
<img width="737" alt="Screen Shot 2021-06-23 at 6 45 27 PM" src="https://user-images.githubusercontent.com/60494758/123177388-2f8bd780-d453-11eb-9405-bb304bc70092.png">

**Comment by CharlieS1103** [comment]
<img width="546" alt="Screen Shot 2021-06-15 at 3 36 38 PM" src="https://user-images.githubusercontent.com/60494758/123177495-6104a300-d453-11eb-839b-143cd294b2b3.png">

**Comment by CharlieS1103** [comment]
Believe it or not, atm nothing that requires a connection at all is working, probably not a bug with this but would appreciate any help with why this is happening

**Comment by AnanthVivekanand** [comment]
Could you start from a fresh git clone and paste a full log of how you set everything up?

**Comment by CharlieS1103** [comment]
@AnanthVivekanand I don't think it's an issue with your app, I figured it out(proxy settings randomly reset.) My setup is spicetify with some custom themes and extensions set up, and I then wrote a script to toggle remove ads, wrapped that in a separate Spotify app(on mac.) for convenience, If it happens again I can always write a small script for recurrently checking the settings, however Logout and Friends list still don't work, which I believe is an issue with the spotify ad block.

**Comment by CharlieS1103** [comment]
It seems to break whenever I hit the logout button, reset the proxy settings and such

**Comment by CharlieS1103** [comment]
It works fine when spicetify is not applied, sorry for the trouble, I'll contact @khanas about it

**Comment by AnanthVivekanand** [comment]
Ok, I wonder why spicetify conflicts with this. Please share any info if you discover anything.

**Comment by CharlieS1103** [comment]
@AnanthVivekanand Will do, I think it's probably something where preferences are saved based on the user signed in so when  I log out the proxy settings are reset and I'm unable to log in, I'm going to look into a way to set the default preferences

**Comment by CharlieS1103** [comment]
@AnanthVivekanand Yeah, I think that Spicetify actually doesn't conflict, but using Spicetify restore backup (resets proxy settings)will fix the issue however you won't be able to log out. I'm confused on a way to fix this other than just stopping your proxy to log out which would be annoying but not impossible, you could potentially implement something to fix this, although I'm not sure what.

**Comment by CharlieS1103** [comment]
The proxy is still up on my computer even after I close the wrapper too which I find odd, I can't even find it in the processes

**Comment by CharlieS1103** [comment]
```
Applications/SpotifyReal.app/Contents/MacOS/SpotifyReal ; exit;
Proxy is up on port 8082
2021-06-23 19:48:24.378 Spotify[2429:21432] This NSLayoutConstraint is being configured with a constant that exceeds internal limits.  A smaller value will be substituted, but this problem should be fixed. Break on BOOL _NSLayoutConstraintNumberExceedsLimit(void) to debug.  This will be logged only once.  This may break in the future.
Allowing: login5.spotify.com
Allowing: apresolve.spotify.com
Allowing: guc3-accesspoint-a-n4f7.ap.spotify.com
Allowing: guc-dealer.spotify.com
Allowing: guc-spclient.spotify.com
Blocked: https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0XC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWVcLzM2LjAuMTk0NC4wIFNhZmFyaVwvNTM3LjM2IFNwb3RpZnlcLzExNjAwMDY3MiAoOTsgMDsgMikiLCJzZXNzaW9uX2lkIjoiZGMyYjgyYmUtMTNkZi00OGY2LWEyYmYtZWEwNGU0NmE2YTA2In0=
Allowing: api-partner.spotify.com
Blocked: https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0XC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWVcLzM2LjAuMTk0NC4wIFNhZmFyaVwvNTM3LjM2IFNwb3RpZnlcLzExNjAwMDY3MiAoOTsgMDsgMikiLCJzZXNzaW9uX2lkIjoiZGMyYjgyYmUtMTNkZi00OGY2LWEyYmYtZWEwNGU0NmE2YTA2In0=
Allowing: xpui.app.spotify.com
Error: getaddrinfo ENOTFOUND xpui.app.spotify.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'xpui.app.spotify.com'
}
Blocked: https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0XC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWVcLzM2LjAuMTk0NC4wIFNhZmFyaVwvNTM3LjM2IFNwb3RpZnlcLzExNjAwMDY3MiAoOTsgMDsgMikiLCJzZXNzaW9uX2lkIjoiZGMyYjgyYmUtMTNkZi00OGY2LWEyYmYtZWEwNGU0NmE2YTA2In0=
Blocked: https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0XC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWVcLzM2LjAuMTk0NC4wIFNhZmFyaVwvNTM3LjM2IFNwb3RpZnlcLzExNjAwMDY3MiAoOTsgMDsgMikiLCJzZXNzaW9uX2lkIjoiZGMyYjgyYmUtMTNkZi00OGY2LWEyYmYtZWEwNGU0NmE2YTA2In0=
Blocked: https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0XC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWVcLzM2LjAuMTk0NC4wIFNhZmFyaVwvNTM3LjM2IFNwb3RpZnlcLzExNjAwMDY3MiAoOTsgMDsgMikiLCJzZXNzaW9uX2lkIjoiZGMyYjgyYmUtMTNkZi00OGY2LWEyYmYtZWEwNGU0NmE2YTA2In0=
Blocked: https://spclient.wg.spotify.com/ad-logic/flashpoint
Blocked: https://spclient.wg.spotify.com/ads/v2/config?payload=eyJ1c2VyX2FnZW50IjoiTW96aWxsYVwvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0XC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWVcLzM2LjAuMTk0NC4wIFNhZmFyaVwvNTM3LjM2IFNwb3RpZnlcLzExNjAwMDY3MiAoOTsgMDsgMikiLCJzZXNzaW9uX2lkIjoiZGMyYjgyYmUtMTNkZi00OGY2LWEyYmYtZWEwNGU0NmE2YTA2In0=

```

**Comment by AnanthVivekanand** [comment]
What is SpotifyReal.app? Is this a modded Spotify?

**Comment by CharlieS1103** [comment]
@AnanthVivekanand It's the wrapper I made to run spotify and  spotify adblock at the same time and together (So i don't have to see spotify adblock console as well.)
