### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by Naramsim** [AnanthVivekanand/spotify-adblock#38]
At work, I'm already using a proxy to browse the Internet.

It would be possible to instruct `spotify-adblock` to use a custom proxy server for outgoing requests?

Thanks

**Comment by AnanthVivekanand** [comment]
I'd say that's out of the scope of this project, but an easy solution might be to use the docker image and specify the proxy servers as so: https://docs.docker.com/network/proxy/

I'm interested to know if this would work, so let me know if it does.

**Comment by Naramsim** [comment]
It doens't seem to work. When starting spotify I see some connections are allowed and refused but ultimately some of the get the ECONNREFUSED error. And Spotify blanks out.
