### ISSUE TITLE
Songlinks don't work

### ISSUE THREAD

**Issue by AutMai** [AnanthVivekanand/spotify-adblock#40]
When I open a songlink in a browser the "site can't be reached. -> refused to connect"
![image](https://user-images.githubusercontent.com/61562414/129188960-2f7f107a-21e3-4ef5-9c2e-431f5ed18c4c.png)

And for example when I send the songlink to a friend on discord where It should generate an "embed" it is just blank. (probably according to the same issue as above (in the browser))
![image](https://user-images.githubusercontent.com/61562414/129189127-3677e033-be83-4165-b162-7b1fc7658aa9.png)

**Comment by AnanthVivekanand** [comment]
This proxy really isn't meant to be used system-wide, especially if you're using the MITM proxy. The MITM proxy will generate a new certificate for each domain, and any good browser would reject the MITM certs. 

This proxy is meant to be used with Spotify's proxy setting. If you want adblocking on open.spotify.com, look into UBlock Origin.

**Comment by AutMai** [comment]
@AnanthVivekanand and so how can I prevent it from blocking system-wide?
