### ISSUE TITLE
Add support for https://cdn.jsdelivr.net

### ISSUE THREAD

**Issue by CharlieS1103** [AnanthVivekanand/spotify-adblock#43]
## Why we need it:
Currently working on a custom app the be implemented by default with spicetify-cli, this custom app will pose as a marketplace for all extensions and themes. The repository is currently private and will be finished in like a month or two. It requires all requests from https://cdn.jsdelivr.net to pass through in order to function at all

**Comment by CharlieS1103** [comment]
I would appreciate it if you would just add these to the whitelists.
```  
"jsdelivr.com", //Remote extension loading on spicetify
  "cdn.jsdelivr.com", //Remote extension loading on spicetify
  "api.github.com",//Github api calls 
  "raw.githubusercontent.com",  //Github content fetching
```

**Comment by AnanthVivekanand** [comment]
Thanks for your contribution, but this almost seems out of the scope for the project. I'd encourage you to fork and add these changes to a downstream fork you could use with your project. From there, you could continue to merge any upstream changes. 

This project is mainly intended to be used stand-alone with vanilla Spotify, and although I commend your efforts on your project, I'd rather keep this repo's functionality focused on regular Spotify. But once again, you're welcome to fork, add your own changes, and continue using upstream changes from here. And keep me updated on your project, I'd love to check it out if you make it public when it's finished. @CharlieS1103
