### ISSUE TITLE
i can't do anything 

### ISSUE THREAD

**Issue by doniwirawan** [AnanthVivekanand/spotify-adblock#45]
![Screen Shot 2021-11-08 at 18 37 00](https://user-images.githubusercontent.com/54931717/140727450-184ba873-6e0d-45be-92a4-080351e1c898.png)

**Comment by Nitchi-ecchi** [comment]
I will suggest that you should use Mitm proxy

**Comment by AnanthVivekanand** [comment]
Try the MITM approach. `index.js` no longer works, I should remove that.
