### ISSUE TITLE
Script Broke..

### ISSUE THREAD

**Issue by Nitchi-ecchi** [AnanthVivekanand/spotify-adblock#48]
the script stopped working, I reinstalled it but no luck, its not even starting at this point

- MITM Proxy
![Screenshot 2021-11-17 at 7 07 06 PM](https://user-images.githubusercontent.com/86887160/142210838-c2bb8776-d08a-4990-a22d-8547cf966fd0.png)

-Normal Proxy
![Screenshot 2021-11-17 at 7 07 42 PM](https://user-images.githubusercontent.com/86887160/142210912-cd429d47-a36e-491b-a6b9-02f62932c194.png)

Spotify is opening without proxy but when I try to open with a proxy, I am getting a black screen
![Screenshot 2021-11-17 at 7 08 47 PM](https://user-images.githubusercontent.com/86887160/142211110-18f411c1-2ade-4e23-b14b-5cc19bbd9ac4.png)

- System Information
OS - Mac m1 Monterey

**Comment by AnanthVivekanand** [comment]
Use mitm.js like your first image and make sure to run `npm i` before `node mitm.js`.
