### ISSUE TITLE
Playback stops when clicking next on songs in playlist

### ISSUE THREAD

**Issue by karelo911** [AnanthVivekanand/spotify-adblock#49]
I have been using your program to block ads on spotify in my mac for a few days now, and it's working perfectly when playing through the songs I search or through the artist pages. However, I noticed that playback stops when I click through a playlist and I click the next button several times. I don't really know how to document this, the song will not play until a minute or so. Is it because of audio ads being blocked?

**Comment by AnanthVivekanand** [comment]
Huh, I've never experienced this issue and I can't replicate it. I tried clicking through songs rapidly on a large playlist and it worked fine for me.

**Comment by karelo911** [comment]
I tried setting Stream Quality to "Auto" and the issue appears to be tolerable now. Sometimes when I click through songs rapidly it would take 5 seconds before playing. It's not likely about my internet connection because they are both wired and running 35mbps down and spotify works just fine on my windows pc with blockthespot. I don't really know how to document/log this as there's nothing unusual in the terminal verbose.

**Comment by karelo911** [comment]
Seems to be working fine now though.
