### ISSUE TITLE
Create discussions for github

### ISSUE THREAD

**Issue by CharlieS1103** [AnanthVivekanand/spotify-adblock#55]
Have some things to talk to you about, including blocking audio ads.
Seems like with this current system there are a lot of conflicts, and I found a way to block audio ads without using anything involving network and was wondering if you would like to be included in the project as I will probably go on to block all other types of ads without involving the network as well (if the system ends up working as intended) Here's my discord. charlieS#1351

**Comment by AnanthVivekanand** [comment]
Alright, I've opened up Github Discussions. I'll contact you through Discord if you want to talk further than through Discussions.
