### ISSUE TITLE
Run on Raspberry Pi for use on multiple machines

### ISSUE THREAD

**Issue by Delta18-Git** [AnanthVivekanand/spotify-adblock#66]
Hi, I just wanted to ask if I would be able to use this in the provided Docker container on a RPi along with a webserver for another application, so that I can use it without having terminal and a server running on my rather slow laptop all the time.

Sorry this is a rather noob question, but I have just gotten back into this after a few years and have totally forgotten everything to do with self-hosted stuff...

**Comment by AnanthVivekanand** [comment]
I don't see anything wrong with running the docker container on an RPi, but you'll have to copy over the root CA to the client computer and trust it as normal.

**Comment by Delta18-Git** [comment]
Oh that's good. Will deploy as soon as my work eases up. Thanks!
