### ISSUE TITLE
"You haven't installed the generated CA certificate"

### ISSUE THREAD

**Issue by NeoHBz** [AnanthVivekanand/spotify-adblock#71]
using a Ubuntu 20.04, free tier Oracle VPS, aarch64 CPU 4-cores
### certificate has been added & activated
<img width="705" alt="image" src="https://user-images.githubusercontent.com/56602090/181995551-48ccc332-4413-4218-b80f-0613f9b46fae.png">

### but mitm still throws this error & exits
<img width="707" alt="image" src="https://user-images.githubusercontent.com/56602090/181995512-f61440d3-1b48-4e1a-920a-605c918495d0.png">

**Comment by cibic89** [comment]
same issue for me on windows 10

**Comment by NeoHBz** [comment]
> on Windows 10+ you need to store certificate in Trusted Root Certification Authority

anything about a Ubuntu VPS?

**Comment by AnanthVivekanand** [comment]
@NeoHBz Are you trying to run the proxy on the VPS? You should trust the Root CA generated on the VPS on the computer where Spotify is actually running.

**Comment by NeoHBz** [comment]
> @NeoHBz Are you trying to run the proxy on the VPS? You should trust the Root CA generated on the VPS on the computer where Spotify is actually running.

yes that is a VPS, and yes I did trust the root CA on the VPS itself

**Comment by AnanthVivekanand** [comment]
@NeoHBz No, I mean, generate the root CA on the VPS, copy it over to your client computer where you're running Spotify, and trust it on the client computer. Whether or not you trust it on the VPS doesn't matter -- you need to trust the same root CA on whatever computer Spotify is running on.
