### ISSUE TITLE
Several adresses are blocked but seem to be vital

### ISSUE THREAD

**Issue by PAXANDDOS** [AnanthVivekanand/spotify-adblock#73]
Hey! I found that several addresses are vital for Spotify, but also if I add them to the whitelist, I will hear ads. They are:
- **api-partner.spotify.com**: if blocked - everything at the Home screen is in a loading state; the Search page won't, Library page contains only placeholders. But I can view and listen to my liked songs and pinned playlists.
- **login5.spotify.com**: the entire application doesn't load. After the 30s-60s, it does load but everything is the same as in the previous one, except that in this case I can view and listen to nothing. It would take an additional ~2min to view a playlist, maybe even longer for a song to start playing
- **seed-mix-image.spotifycdn.com**: blocks all Mixes images. I reckon this should be added to the whitelist.
- **gew1-spclient.spotify.com**: adds some kind of a pause (~5s) before the song starts playing, everything else works.
- **gew1-dealer.spotify.com**: same as above. When blocked together they produce the same effect as with _api-partner.spotify.com_

When everything mentioned above is whitelisted, the application works as expected, but ads are still there.
I hope you can think of something with that info, you've made a good tool so far!

My environment:
- Windows 11 22H2
- Spotify of the latest version from the Microsoft Store
- Regular version of your tool

**Comment by AnanthVivekanand** [comment]
Were you using `mitm.js` or `index.js`?

**Comment by PAXANDDOS** [comment]
I was using `index.js` , couldn't get `mitm.js` one to work unfortunately. Anyways I already went for a more complicated way - bought myself a Raspberry Pi and now using a Pi-hole
